#ifndef TERRITORIES_H
#define TERRITORIES_H

#define EUROPE_MAP  0
#define PACIFIC_MAP 1

// Europe map territories
// North America
#define TER_ALBERTA      0
#define TER_ONTARIO      1
#define TER_QUEBEC       2
#define TER_NEWFOUNDLAND 3
#define TER_NEW_BRUNS    4
#define TER_GREENLAND    5
#define TER_CENTRAL_USA  6
#define TER_EASTERN_USA  7
#define TER_SE_MEXICO    8
#define TER_WEST_INDIES  9
#define TER_CENT_AMERICA 10

// South America
#define TER_VENEZUELA    11
#define TER_COLOMBIA     12
#define TER_BRIT_GUIANA  13
#define TER_SURINAME     14
#define TER_FRA_GUIANA   15
#define TER_ECUADOR      16
#define TER_PERU         17
#define TER_BOLIVIA      18
#define TER_BRAZIL       19
#define TER_PARAGUAY     20
#define TER_URUGUAY      21
#define TER_ARGENTINA    22
#define TER_CHILE        23

// Europe
#define TER_ICELAND      24
#define TER_SCOTLAND     25
#define TER_EIRE         26
#define TER_UTD_KINGDOM  27
#define TER_DENMARK      28
#define TER_HOLL_BELG    29
#define TER_WEST_GERMANY 30
#define TER_FRANCE       31
#define TER_SWITZERLAND  32
#define TER_NORMANDY     33
#define TER_SOUTH_FRANCE 34
#define TER_SPAIN        35
#define TER_PORTUGAL     36
#define TER_GIBRALTAR    37
#define TER_SARDINIA     38
#define TER_NORWAY       39
#define TER_SWEDEN       40
#define TER_FINLAND      41
#define TER_NORTH_ITALY  42
#define TER_SOUTH_ITALY  43
#define TER_SICILY       44
#define TER_GERMANY      45
#define TER_S_GERMANY    46
#define TER_POLAND       47
#define TER_SLOV_HUNGARY 48
#define TER_YUGOSLAVIA   49
#define TER_ALBANIA      50
#define TER_GREECE       51
#define TER_CRETE        52
#define TER_ROMANIA      53
#define TER_BULGARIA     54
#define TER_BALTIC_STATE 55
#define TER_EAST_POLAND  56
#define TER_KARELIA      57
#define TER_VYBORG       58
#define TER_NOVGOROD     59
#define TER_BELARUS      60
#define TER_WEST_UKRAINE 61
#define TER_BESSARABIA   62
#define TER_ARCHANGEL    63
#define TER_SMOLENSK     64
#define TER_BRYANSK      65
#define TER_UKRAINE      66
#define TER_ROSTOV       67
#define TER_CAUCASUS     68
#define TER_NENETSIA     69
#define TER_VOLOGDA      70
#define TER_RUSSIA       71
#define TER_TAMBOV       72
#define TER_VOLGOGRAD    73
#define TER_URALS        74
#define TER_NOVOSIBIRSK  75
#define TER_SAMARA       76
#define TER_KAZAKHSTAN   77
#define TER_TURKMENISTAN 78

// Africa
#define TER_MOROCCO      79
#define TER_ALGERIA      80
#define TER_TUNISIA      81
#define TER_RIO_DE_ORO   82
#define TER_PORT_GUINEA  83
#define TER_FRA_W_AFRICA 84
#define TER_FRA_C_AFRICA 85
#define TER_SIERRA_LEONE 86
#define TER_LIBERIA      87
#define TER_GOLD_COAST   88
#define TER_NIGERIA      89
#define TER_LIBYA        90
#define TER_MALTA        91
#define TER_TOBRUK       92
#define TER_ALEXANDRIA   93
#define TER_EGYPT        94
#define TER_FR_EQ_AFRICA 95
#define TER_AN_EGY_SUDAN 96
#define TER_ETHIOPIA     97
#define TER_BRIT_SOMALI  98
#define TER_ITAL_SOMALI  99
#define TER_BELG_CONGO   100
#define TER_KENYA        101
#define TER_TANGANYIKA   102
#define TER_ANGOLA       103
#define TER_RHODESIA     104
#define TER_MOZAMBIQUE   105
#define TER_SW_AFRICA    106
#define TER_SOUTH_AFRICA 107
#define TER_MADAGASCAR   108

// Middle East
#define TER_TURKEY       109
#define TER_CYPRUS       110
#define TER_SYRIA        111
#define TER_TRANS_JORDAN 112
#define TER_IRAQ         113
#define TER_SAUDI_ARABIA 114
#define TER_NW_PERSIA    115
#define TER_PERSIA       116
#define TER_EAST_PERSIA  117
#define TER_AFGHANISTAN  118
#define TER_WEST_INDIA   119

//// Pacific Map territories
// Asia
#define TER_EVENKIYSKIY  120
#define TER_YENISEY      121
#define TER_YAKUT        122
#define TER_BURYATIA     123
#define TER_SAKHA        124
#define TER_AMUR         125
#define TER_SIBERIA      126
#define TER_SOV_FAR_EAST 127
#define TER_TIMGUSKA     128
#define TER_OLGIY        129
#define TER_DZAVHAN      130
#define TER_TSAGAAN_OLOM 131
#define TER_CNT_MONGOLIA 132
#define TER_ULAANBAATAR  133
#define TER_BUYANT_UHAA  134
#define TER_KANSU        135
#define TER_SUIYUAN      136
#define TER_CHAHAR       137
#define TER_JEHOL        138
#define TER_MANCHURIA    139
#define TER_KOREA        140
#define TER_TSINGHAI     141
#define TER_SHENSI       142
#define TER_HOPEI        143
#define TER_ANHWE        144
#define TER_SHANTUNG     145
#define TER_KIANGSU      146
#define TER_SIKANG       147
#define TER_SZECHWAN     148
#define TER_KWEICHOW     149
#define TER_HUNAN        150
#define TER_KIANGSI      151
#define TER_YUNNAN       152
#define TER_KWANGSI      153
#define TER_KWANGTUNG    154
#define TER_INDIA        155
#define TER_CEYLON       156
#define TER_BURMA        157
#define TER_SHAN_STATE   158
#define TER_SIAM         159
#define TER_FR_IND_CHINA 160
#define TER_MALAYA       161

// Australia and New Zealand
#define TER_W_AUSTRALIA  162
#define TER_N_TERRITORY  163
#define TER_S_AUSTRALIA  164
#define TER_QUEENSLAND   165
#define TER_NEW_S_WALES  166
#define TER_VICTORIA     167
#define TER_NEW_ZEALAND  168

// Pacific
#define TER_JAPAN        169
#define TER_OKINAWA      170
#define TER_IWO_JIMA     171
#define TER_MIDWAY       172
#define TER_FORMOSA      173
#define TER_MARIANAS     174
#define TER_WAKE_ISLAND  175
#define TER_HAWAII       176
#define TER_GUAM         177
#define TER_MARSHALL_ISL 178
#define TER_JOHNSTON_ISL 179
#define TER_LINE_ISLANDS 180
#define TER_GILBERT_ISL  181
#define TER_FIJI         182
#define TER_SAMOA        183
#define TER_NEW_HEBRIDES 184
#define TER_SOLOMON_ISL  185
#define TER_NEW_BRITAIN  186
#define TER_NEW_GUINEA   187
#define TER_DUT_N_GUINEA 188
#define TER_CAROLINE_ISL 189
#define TER_PALAU_ISL    190
#define TER_PHILIPPINES  191
#define TER_CELEBES      192
#define TER_BORNEO       193
#define TER_JAVA         194
#define TER_SUMATRA      195
#define TER_HAINAN       196

// North America 
#define TER_ALASKA       197
#define TER_ALEUTIAN_ISL 198
#define TER_W_CANADA     199
#define TER_WESTERN_USA  200
#define TER_MEXICO       201

#endif
