#include "Territories.h"

int neutrals[44] = { TER_VENEZUELA, TER_COLOMBIA, TER_SURINAME, TER_ECUADOR,
TER_PERU, TER_BOLIVIA, TER_BRAZIL, TER_PARAGUAY,
TER_URUGUAY, TER_ARGENTINA, TER_CHILE, TER_EIRE,
TER_SWITZERLAND, TER_SPAIN, TER_PORTUGAL, TER_SWEDEN,
TER_FINLAND, TER_YUGOSLAVIA, TER_GREECE, TER_CRETE,
TER_BULGARIA, TER_RIO_DE_ORO, TER_PORT_GUINEA,
TER_SIERRA_LEONE, TER_LIBERIA, TER_ANGOLA, TER_MOZAMBIQUE,
TER_TURKEY, TER_IRAQ, TER_SAUDI_ARABIA, TER_NW_PERSIA,
TER_PERSIA, TER_EAST_PERSIA, TER_AFGHANISTAN, TER_OLGIY,
TER_DZAVHAN, TER_TSAGAAN_OLOM, TER_CNT_MONGOLIA,
TER_ULAANBAATAR, TER_BUYANT_UHAA, TER_DUT_N_GUINEA,
TER_CELEBES, TER_JAVA, TER_SUMATRA };